### ISSUE TITLE
Change the way conditions are written.

### ISSUE THREAD

**Issue by NSG650** [ivan123gm/some-random-robot#1]
Please change the way how you used if and else ifs from
```js
if (command === 'ping')
{message.reply('pong!')}
else if (command === 'hello')
{message.reply('hello!')}
```
to

```js
if(command === "ping"){
    message.reply('pong!')
}
else if(command === "hello"){
    message.reply('hello!')
}
```
thanks and regards
NSG650

**Comment by ivan123gm** [comment]
Thanks, i will change my code.

**Comment by ivan123gm** [comment]
Done. I changed my code.
Link to the commit: [here](https://github.com/ivan123gm/some-random-robot/commit/71fa19c08ab927044ad83c1b5311c9a2f601874b)
